version: "3"
services:
  wallet:
    image: nginx:1.15.3-alpine
    restart: always
    working_dir: /home/static
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf # 挂载 nginx 配置文件
      - ./public/dist:/home/static # 挂载静态文件
    ports:
      - 10080:80 # 绑定容器的80端口到本的1080端口
